In [1]:
a = 1 

In [2]:
import numpy as np

#### Exo 1

In [3]:
# Create a NumPy array of shape (5, 5) filled with random integers
my_array = np.random.randint(1, 21, size=(5,5))

print("Original array :")
my_array

Original array :


array([[ 3,  7,  4,  7, 20],
       [ 9, 12, 16, 10, 14],
       [ 1, 13, 15,  4, 17],
       [17, 11, 16, 15,  1],
       [14, 11, 10, 13, 20]], dtype=int32)

In [4]:
#Replace all the elements in the third column with 1
my_array[:,2]= 1

print("Modified array :")
my_array

Modified array :


array([[ 3,  7,  1,  7, 20],
       [ 9, 12,  1, 10, 14],
       [ 1, 13,  1,  4, 17],
       [17, 11,  1, 15,  1],
       [14, 11,  1, 13, 20]], dtype=int32)

##### Exo 2

In [5]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
my_array = np.random.randint(1, 17, size=(4, 4))

print("Original array :")
my_array

Original array :


array([[15, 15, 10,  1],
       [ 7, 11, 11, 16],
       [ 4,  5, 15,  4],
       [16,  1,  5,  9]], dtype=int32)

In [6]:
# Replace the diagonal elements with 0
np.fill_diagonal(my_array, 0)

print("Modified array :")
my_array

Modified array :


array([[ 0, 15, 10,  1],
       [ 7,  0, 11, 16],
       [ 4,  5,  0,  4],
       [16,  1,  5,  0]], dtype=int32)

#### Exo 3

In [7]:
my_array = np.arange(1, 37).reshape(6, 6)
print("Original array :\n")
print(my_array)

Original array :

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [8]:
# Extract the sub-array

sub_array = my_array[2:5, 1:4]

print("Modified array :\n")
print(sub_array)

Modified array :

[[14 15 16]
 [20 21 22]
 [26 27 28]]


#### Exo 4

In [9]:
array = np.random.randint(1, 21, size=(5,5))

print("Original array :\n")
print(array)

Original array :

[[12 20 14  1 12]
 [13 11  8 14 19]
 [ 4  8 18  5  4]
 [ 4  4 19 11 16]
 [ 7 18  5  7  2]]


In [10]:
border1 = array[:,-1]
print(border1)

[12 19  4 16  2]


In [11]:
border2 = array[:, 0]
print(border2)

[12 13  4  4  7]


In [12]:
border3 = array[0,:]
print(border3)

[12 20 14  1 12]


In [13]:
border4 = array[4,:]
print(border4)

[ 7 18  5  7  2]


In [14]:
border5 = [border1, border2, border3, border4]
print(border5)

[array([12, 19,  4, 16,  2], dtype=int32), array([12, 13,  4,  4,  7], dtype=int32), array([12, 20, 14,  1, 12], dtype=int32), array([ 7, 18,  5,  7,  2], dtype=int32)]


In [15]:
border_elements = np.concatenate((border1, border2, border3, border4))
print(border_elements)

[12 19  4 16  2 12 13  4  4  7 12 20 14  1 12  7 18  5  7  2]


#### Exo 5

In [16]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 13, size=(3,4))
array2 = np.random.randint(1, 13, size=(3,4))

print("Premier array :\n")
print(array1)

print("Second array :\n")
print(array2)

Premier array :

[[9 5 2 2]
 [3 7 1 4]
 [5 2 3 3]]
Second array :

[[ 7  3 10  5]
 [10  1  9  1]
 [ 6  3  7  6]]


In [17]:
#Opérations
#Addition
print("La somme des deux est :\n")
print(array1 + array2, '\n')

print("La soustraction des deux est :\n")
print(array1 - array2, '\n')

print("La division des deux est :\n")
print(array1 / array2,'\n')

print("La multiplication des deux est :\n")
print(array1 * array2)

La somme des deux est :

[[16  8 12  7]
 [13  8 10  5]
 [11  5 10  9]] 

La soustraction des deux est :

[[ 2  2 -8 -3]
 [-7  6 -8  3]
 [-1 -1 -4 -3]] 

La division des deux est :

[[1.28571429 1.66666667 0.2        0.4       ]
 [0.3        7.         0.11111111 4.        ]
 [0.83333333 0.66666667 0.42857143 0.5       ]] 

La multiplication des deux est :

[[63 15 20 10]
 [30  7  9  4]
 [30  6 21 18]]


#### Exo 6

In [18]:
array = np.arange(1, 17).reshape(4, 4)

print("Original array :\n")
print(array)

Original array :

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [19]:
#somme des lignes
rows_sum = np.sum(array, axis=1)

print(f"Somme des lignes : {rows_sum} \n")

#somme des colonnes
columns_sum = np.sum(array, axis=0)
print(f"Somme des colonnes : {columns_sum} \n")

Somme des lignes : [10 26 42 58] 

Somme des colonnes : [28 32 36 40] 



#### Exo 7

In [20]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(5, 26, size=(5,5))
print("Original array :\n")
print(array)

Original array :

[[15 22 13 14  7]
 [15  5 22  5  7]
 [23  5 15 20 11]
 [17 13 22  8 17]
 [ 9 25 14 19 22]]


In [21]:
array_mean = np.mean(array)
array_median = np.median(array)
array_std_deviation = np.std(array)
array_variance = np.var(array)

print(f"La moyenne : {array_mean} \n")
print(f"La mediane : {array_median} \n")
print(f"La deviation standard : {array_std_deviation}\n")
print(f"La variance : {array_variance} \n")

La moyenne : 14.6 

La mediane : 15.0 

La deviation standard : 6.144916598294887

La variance : 37.76 



#### Exo 8

In [22]:
array = np.arange(1, 10).reshape(3, 3)
print("Original array :\n")
print(array)

Original array :

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


#### Exo9

In [24]:
array = np.random.randint(1, 10, size=(3,3))
print("The original array :\n")
print(array)

The original array :

[[2 3 4]
 [7 4 5]
 [4 3 4]]


In [25]:
#One dimension array
one_dimension_array = np.random.randint(1, 10, size=(3,))
print("The one dimension array :\n")
print(one_dimension_array)

The one dimension array :

[5 4 9]


In [26]:
for x in array:
    print( x + one_dimension_array)

[ 7  7 13]
[12  8 14]
[ 9  7 13]


In [27]:
#Une autre façon de le faire
result = one_dimension_array + array

print(result)

[[ 7  7 13]
 [12  8 14]
 [ 9  7 13]]


#### Exo 10

In [28]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 17, size=(4, 4))
one_d_array = np.random.randint(1, 17, size=(4,))

print("The 2D array :\n")
print(array, '\n')

print("The 1D array :\n")
print(one_d_array)

The 2D array :

[[11  4  3 16]
 [ 1 12  4 10]
 [ 3  6  5 16]
 [ 3  9  6  8]] 

The 1D array :

[13  8 12 13]


In [29]:
#Soustarction 1D - 2D
soustra = array - one_d_array
print("The last array :\n")
print(soustra)

The last array :

[[ -2  -4  -9   3]
 [-12   4  -8  -3]
 [-10  -2  -7   3]
 [-10   1  -6  -5]]


#### Exo11

In [30]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 10, size=(3, 3))
print("The matrix :\n")
print(matrix)

The matrix :

[[7 6 6]
 [8 9 5]
 [6 6 4]]


In [31]:
# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Determinant: -6.000000000000003
Inverse:
[[-1.         -2.          4.        ]
 [ 0.33333333  1.33333333 -2.16666667]
 [ 1.          1.         -2.5       ]]
Eigenvalues: [19.31070844 -0.31070844  1.        ]


#### Exo 12

In [32]:
array1 = np.random.randint(1, 7, size=(2, 3))
array2 = np.random.randint(1, 7, size=(3, 2))

print("Array 1 :\n")
print(array1, '\n')

print("Array 2: \n")
print(array2)

Array 1 :

[[2 1 1]
 [3 6 2]] 

Array 2: 

[[3 2]
 [4 6]
 [4 4]]


In [33]:
# Perform matrix multiplication

arr = np.dot(array1, array2)
print(arr)

[[14 14]
 [41 50]]


#### Exo 13

In [34]:
array = np.arange(1, 10).reshape(3, 3)

print("Array 1 :\n")
print(array, '\n')

array2 = array.reshape(1, 9)

print("Array 2 :\n")
print(array2, '\n')

array3 = array.reshape(9, 1)

print("Array 3 :\n")
print(array3)

Array 1 :

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Array 2 :

[[1 2 3 4 5 6 7 8 9]] 

Array 3 :

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


#### Exo 14

In [35]:
array = np.random.randint(5, 26, size=(5, 5))

print("The original array :\n")
print(array)

The original array :

[[16 25 22  7  7]
 [18 17 21 17 19]
 [16  8 17  5 23]
 [15  5 25 24 14]
 [13 16  7  7 16]]


In [36]:
#Flatten array

array_flatten = array.flatten()
print("Flatten array :\n")
print(array_flatten, '\n')

# Reshape the array back to (5, 5)
reshaped_array = array_flatten.reshape(5, 5)
print("Reshape array :\n")
print(reshaped_array)

Flatten array :

[16 25 22  7  7 18 17 21 17 19 16  8 17  5 23 15  5 25 24 14 13 16  7  7
 16] 

Reshape array :

[[16 25 22  7  7]
 [18 17 21 17 19]
 [16  8 17  5 23]
 [15  5 25 24 14]
 [13 16  7  7 16]]


#### Exo 15

In [37]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("The original array :\n")
print(array)

The original array :

[[16  5 11  7  7]
 [ 8  8 20 12  6]
 [18 16  3 14 19]
 [18  2 19  8 16]
 [17  7 15 20 17]]


In [39]:
# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Corner elements:
[14 10 15 14]


#### Exo 16

In [38]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))

print("The original array :\n")
print(array)

The original array :

[[ 8  4 18 14]
 [19 13 19  5]
 [16  4  4  7]
 [ 2  1 19  2]]


In [39]:
# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10

print("New array :\n")
print(array)

New array :

[[ 8  4 10 10]
 [10 10 10  5]
 [10  4  4  7]
 [ 2  1 10  2]]
