In [1]:
a = 1

In [2]:
print(a)

1


#### Exos

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [50]:
array = np.random.randint(1, 25, size=(6, 4))

print(array, '\n')

df = pd.DataFrame(array)

print("Le Dataframe :\n")
print(df)

[[10 21 14 22]
 [ 3 12  5 21]
 [17 14 20 24]
 [ 3  1  2 19]
 [22  7  7 12]
 [ 5 10 14 24]] 

Le Dataframe :

    0   1   2   3
0  10  21  14  22
1   3  12   5  21
2  17  14  20  24
3   3   1   2  19
4  22   7   7  12
5   5  10  14  24


In [6]:
# Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)), columns=['A', 'B', 'C', 'D'])
print("Original DataFrame:")
print(df)

# Set the index to be the first column
df.set_index('A', inplace=True)
print("DataFrame with new index:")
print(df)

Original DataFrame:
    A   B   C   D
0  55  98  52  72
1  31  99  65  69
2  24  83  20  55
3  55  62  79   5
4  72  25  71  41
5  40  40  19  35
DataFrame with new index:
     B   C   D
A             
55  98  52  72
31  99  65  69
24  83  20  55
55  62  79   5
72  25  71  41
40  40  19  35


#### Exo 2

In [7]:
df = pd.DataFrame(np.random.randint(1, 10, size=(3, 3)), columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])

print("The original dataframe :\n")
print(df)

The original dataframe :

   A  B  C
X  3  9  1
Y  3  9  9
Z  6  6  2


In [8]:
#Accessing element at row y and column b
element = df.at['Y', 'B']
print(f"The element at row 'Y' and column 'B' is : {element}")

The element at row 'Y' and column 'B' is : 9


### Exo 3

In [9]:
df = pd.DataFrame(np.random.randint(1, 15, size=(5, 3)), columns=['A', 'B', 'C'])

print("The original Dataframe :\n")
print(df)

The original Dataframe :

    A   B   C
0  14   9   6
1   8   5   5
2  11   1  13
3   1  10   1
4   8   6  13


In [10]:
#Ajout colonne
df['D'] = df['A'] * df['B']

print("Ajout d'une nouvelle colonne :\n")
print(df)

Ajout d'une nouvelle colonne :

    A   B   C    D
0  14   9   6  126
1   8   5   5   40
2  11   1  13   11
3   1  10   1   10
4   8   6  13   48


#### Exo 4

In [11]:
df = pd.DataFrame(np.random.randint(1, 13, size=(4, 3)), columns=['A', 'B', 'C'])

print("The original Dataframe :\n")
print(df)

The original Dataframe :

    A   B   C
0  12  11   7
1   7   4   8
2   2   2  10
3  12   7   3


In [13]:
#sommes des lignes
rows_sum = df.sum(axis=1)
columns_sum = df.sum(axis=0)

print(f"Somme des lignes :  \n")
print(rows_sum, '\n')
print(f"Somme des colonnes : \n")
print(columns_sum)

Somme des lignes :  

0    30
1    19
2    14
3    22
dtype: int64 

Somme des colonnes : 

A    33
B    24
C    28
dtype: int64


#### Exo 5

In [14]:
#Data cleaning
df = pd.DataFrame(np.random.randint(1, 16, size=(5,3)), columns=['A', 'B', 'C'])

print("The original Dataframe :\n")
print(df)

The original Dataframe :

    A   B   C
0   3   4   1
1   6  14   5
2   1  10   5
3  15   6  10
4  13   4   4


In [22]:
#Introdruire des valeurs manquantes 
df.iloc[0,1] = np.nan
df.iloc[4,2] = np.nan
df.iloc[2,1] = np.nan
df.iloc[4,0] = np.nan

In [23]:
print(df)

      A     B     C
0   3.0   NaN   1.0
1   6.0  14.0   5.0
2   1.0   NaN   5.0
3  15.0   6.0  10.0
4   NaN   4.0   NaN


In [28]:
#Remplir les #NA
df.fillna(df.mean(), inplace=True)


In [29]:
print(df)

       A        B      C
0   3.00   6.2500   1.00
1   6.00  14.0000   5.00
2   1.00   7.5625   5.00
3  15.00   6.0000  10.00
4   6.25   4.0000   5.25


#### Exo 6

In [53]:
df = pd.DataFrame(np.random.randint(4, 25, size=(6, 4)), columns=['A', 'B', 'C', 'D'])
print("The original Dataframe :\n")
print(df)

The original Dataframe :

    A   B   C   D
0  21   9  11   8
1  16  24  14  17
2   7  21  23   4
3   5  15   9  17
4  10  23  14  11
5   4   4  22  14


In [54]:
#Adding some #NA values 
df.iloc[0,0] = np.nan
df.iloc[5,3] = np.nan
df.iloc[2,2] = np.nan
df.iloc[5,1] = np.nan
df

A     B     C     D
0   NaN   9.0  11.0   8.0
1  16.0  24.0  14.0  17.0
2   7.0  21.0   NaN   4.0
3   5.0  15.0   9.0  17.0
4  10.0  23.0  14.0  11.0
5   4.0   NaN  22.0   NaN

In [58]:
#drop #NA values (on va supprimer les lignes avec des #NA)
df.dropna(inplace=True)

print("The Dataframe with droped values :")
df

The Dataframe with droped values :


A     B     C     D
1  16.0  24.0  14.0  17.0
3   5.0  15.0   9.0  17.0
4  10.0  23.0  14.0  11.0

#### Exo 7

In [59]:
!pip install pandas

In [60]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'
df = pd.DataFrame({'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Value': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
print(df)

Original DataFrame:
  Category  Value
0        A     73
1        C     21
2        C      3
3        C     82
4        A     84
5        A     54
6        B     21
7        A     49
8        C     23
9        A     24


In [3]:
# Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category
grouped = df.groupby('Category')['Value'].agg(['sum', 'mean'])
print("Grouped DataFrame:")
print(grouped)

Grouped DataFrame:
          sum   mean
Category            
A         284  56.80
B          21  21.00
C         129  32.25


In [5]:
import pandas as pd
import numpy as np

In [6]:
# Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'
df = pd.DataFrame({'Product' : np.random.choice(['Iphone 14', 'Hp Elite Book', 'PS5'], size=10), 'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Sales' :np.random.randint(1, 25, size=10)})

print("The original Dataframe :\n")
print(df)

The original Dataframe :

         Product Category  Sales
0            PS5        C     14
1  Hp Elite Book        C     20
2  Hp Elite Book        B      4
3  Hp Elite Book        B     12
4            PS5        A     18
5            PS5        C     14
6      Iphone 14        A      5
7            PS5        C     17
8            PS5        C     11
9  Hp Elite Book        B     19


In [7]:
# Group the DataFrame by 'Category' and compute the total sales for each category

grouped = df.groupby('Category')['Sales'].sum()

print("Groupement par catégorie :\n")
print(grouped)

Groupement par catégorie :

Category
A    23
B    35
C    76
Name: Sales, dtype: int32


#### Exo 8

In [8]:
df1 = pd.DataFrame({'Category':['A', 'B', 'C', 'D'], 'Value' : np.random.randint(1, 100, size=4)})
df2 = pd.DataFrame({'Category':['A', 'F', 'C', 'E'], 'Value' : np.random.randint(1, 100, size=4)})

print("The first dataframe :\n")
print(df1, '\n')

print("The second dataframe :\n")
print(df2)



The first dataframe :

  Category  Value
0        A     37
1        B     79
2        C     57
3        D     20 

The second dataframe :

  Category  Value
0        A     43
1        F     90
2        C     62
3        E     41


In [9]:
#merger les deux Dataframe
merged = pd.merge(df1, df2, on='Category')
print(merged)

  Category  Value_x  Value_y
0        A       37       43
1        C       57       62
